var main, numTypes, printError, isPositiveIntegerNumber, isPositiveRealNumber, ref$, isinteger, info, print;
main = require("./main.js");
numTypes = main.numTypes, printError = main.printError;
isPositiveIntegerNumber = numTypes.isPositiveIntegerNumber, isPositiveRealNumber = numTypes.isPositiveRealNumber;
ref$ = isPositiveIntegerNumber(function(){}), isinteger = ref$[0], info = ref$[1];
console.log(isinteger);
console.log(info);
ref$ = isPositiveIntegerNumber({}), isinteger = ref$[0], info = ref$[1];
console.log(isinteger);
console.log(info);
ref$ = isPositiveIntegerNumber(undefined), isinteger = ref$[0], info = ref$[1];
console.log(isinteger);
console.log(info);
ref$ = isPositiveIntegerNumber(null), isinteger = ref$[0], info = ref$[1];
console.log(isinteger);
console.log(info);
ref$ = isPositiveIntegerNumber([]), isinteger = ref$[0], info = ref$[1];
console.log(isinteger);
console.log(info);
ref$ = isPositiveIntegerNumber(1), isinteger = ref$[0], info = ref$[1];
console.log(isinteger);
console.log(info);
ref$ = isPositiveIntegerNumber(1.3), isinteger = ref$[0], info = ref$[1];
console.log(isinteger);
console.log(info);
ref$ = isPositiveIntegerNumber(-1.3), isinteger = ref$[0], info = ref$[1];
console.log(isinteger);
console.log(info);
console.log("\n\n\n\n\n\n\n\n\n\n\n\n");
print = printError.create("hello", "world");
print.throwTypeError("hello");