var main, numTypes, printError, isPositiveIntegerNumber, isPositiveRealNumber, ref$, isinteger, info;
main = require("./main.js");
numTypes = main.numTypes, printError = main.printError;
isPositiveIntegerNumber = numTypes.isPositiveIntegerNumber, isPositiveRealNumber = numTypes.isPositiveRealNumber;
ref$ = isPositiveIntegerNumber(1), isinteger = ref$[0], info = ref$[1];
console.log(isinteger);
console.log(info);
ref$ = isPositiveIntegerNumber(1.3), isinteger = ref$[0], info = ref$[1];
console.log(isinteger);
console.log(info);